[package]
name = "isophes/deknit"
description = "DeKnit is a lightweight game framework forked from Sleitnick's Knit module"
version = "2.0.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["iSophes", "Stephen Leitnick"]

[dependencies]
Comm = "sleitnick/comm@^1"
Promise = "evaera/promise@^4"
